"""added revoked token model

Revision ID: 12dbd350612c
Revises: e91bd15ae2ce
Create Date: 2026-02-09 19:22:55.024137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12dbd350612c'
down_revision: Union[str, Sequence[str], None] = 'e91bd15ae2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token_model',
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('datetime_ttl', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('datetime_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_token_model')
    # ### end Alembic commands ###
