"""user_model_fixed

Revision ID: e91bd15ae2ce
Revises: 0a2b710e0f8d
Create Date: 2026-02-06 19:08:11.329303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91bd15ae2ce'
down_revision: Union[str, Sequence[str], None] = '0a2b710e0f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authid_model',
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('datetime_ttl', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('datetime_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('user_model',
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.String(length=32), nullable=False),
    sa.Column('datetime_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_deactivated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authid_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('datetime_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authid_id'], ['authid_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authid_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    op.drop_table('authid_model')
    # ### end Alembic commands ###
