NAME_MIN_LENGTH: int = 3
NAME_MAX_LENGTH: int = 64
AUTHID_MIN_LENGTH: int = 64
AUTHID_MAX_LENGTH: int = 128
PID_MIN_LENGTH: int = 16
PID_MAX_LENGTH: int = 32
EMAIL_MIN_LENGTH: int = 5
EMAIL_MAX_LENGTH: int = 255